"""Regression test: CadQuery scripts must run even if they omit `import
cadquery as cq`, because the prompt promises it's already available.
"""
from pathlib import Path
import tempfile

from cad.cadquery_engine import CadQueryEngine


SCRIPT_NO_IMPORT = """\
# Generated by an LLM that followed the prompt — skipped the import because
# the system prompt says `import cadquery as cq` is "already available".
result = cq.Workplane("XY").box(10, 10, 10).val()
result = cq.Workplane("XY").box(10, 10, 10)
"""


SCRIPT_WITH_IMPORT = """\
import cadquery as cq
result = cq.Workplane("XY").box(10, 10, 10)
"""


SCRIPT_USES_MATH = """\
# math should also be available even without an explicit import
result = cq.Workplane("XY").circle(5).extrude(math.sin(0) + 10)
"""


def _run(script_text: str) -> dict:
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as f:
        f.write(script_text)
        sp = Path(f.name)
    out = Path(tempfile.mkdtemp())
    eng = CadQueryEngine()
    geom = eng.execute(sp, out)
    return {"ok": geom.step_path.exists(),
            "step_bytes": geom.step_path.stat().st_size if geom.step_path.exists() else 0,
            "volume_mm3": geom.volume_mm3}


def test_script_without_import_runs():
    """The LLM prompt says `import cadquery as cq` is already available —
    the engine must honour that promise."""
    r = _run(SCRIPT_NO_IMPORT)
    assert r["ok"], "Script without `import cadquery as cq` should run"
    assert r["step_bytes"] > 0
    assert abs(r["volume_mm3"] - 1000.0) < 0.1   # 10x10x10 mm


def test_script_with_import_still_runs():
    """If the LLM includes the import, it must not break."""
    r = _run(SCRIPT_WITH_IMPORT)
    assert r["ok"]
    assert abs(r["volume_mm3"] - 1000.0) < 0.1


def test_math_is_preloaded():
    """Same promise for math — scripts that use math without importing it work."""
    r = _run(SCRIPT_USES_MATH)
    assert r["ok"]