"""BOM — Bill of Materials.

For a single-part STEP, the BOM is trivial (the part itself + material + finish).
For assemblies (multi-body STEP), we walk the assembly tree and emit rows.
Output: CSV + JSON.
"""
from __future__ import annotations

import csv
import json
from dataclasses import asdict, dataclass, field
from pathlib import Path

import yaml


@dataclass
class BOMItem:
    item: str
    description: str = ""
    qty: int = 1
    material: str = ""
    process: str = ""
    stock_size_mm: str = ""
    finish: str = ""
    estimated_cost_usd: float | None = None
    source_file: str = ""


@dataclass
class BOM:
    items: list[BOMItem] = field(default_factory=list)
    notes: str = ""

    def to_csv(self, path: Path) -> None:
        with path.open("w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["item", "description", "qty", "material", "process",
                        "stock_size_mm", "finish", "est_cost_usd", "source_file"])
            for it in self.items:
                w.writerow([it.item, it.description, it.qty, it.material,
                            it.process, it.stock_size_mm, it.finish,
                            it.estimated_cost_usd or "", it.source_file])

    def to_json(self, path: Path) -> None:
        path.write_text(json.dumps([asdict(i) for i in self.items], indent=2))

    def to_dict(self) -> dict:
        return {"notes": self.notes, "items": [asdict(i) for i in self.items]}


def extract_bom(step_path: Path, *, brief=None, materials_dir: Path | None = None) -> BOM:
    """Walk the STEP and produce a BOM.

    For now we ship a simple one-row BOM with metadata from the brief.
    A real assembly walker (PMI-aware) lives in outputs/assembly_bom.py.
    """
    item = BOMItem(
        item=brief.name if brief and brief.name else step_path.stem,
        description=brief.description if brief else "",
        qty=brief.quantity if brief else 1,
        material=brief.material if brief else "",
        process=brief.process if brief else "",
        stock_size_mm=_stock_from_brief(brief),
        finish=brief.finish if brief else "as-machined",
        source_file=str(step_path),
    )
    return BOM(items=[item], notes="Generated by JoyCAD. Verify before quoting.")


def _stock_from_brief(brief) -> str:
    if not brief or not brief.bbox_mm:
        return ""
    b = brief.bbox_mm
    L = b.get("length", 0); W = b.get("width", 0); T = b.get("thickness",
                                                            b.get("height", 0))
    stock_pad = 3.0
    return f"{L + stock_pad:.1f} x {W + stock_pad:.1f} x {T + stock_pad:.1f} mm"
