"""Manufacturing notes — LLM-generated human-readable doc.

Takes the structured brief, geometry metrics, and validation reports, and
asks the LLM to write a Markdown document with setup notes, tool list,
feeds & speeds, quality checks, and known risks.

Falls back to a template if the LLM is unavailable — never silent fail.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from loguru import logger

from ai.llm_client import llm_factory


SYSTEM = """You are a senior CNC machinist writing manufacturing notes.
Given a structured design brief, geometry metrics, and validation reports,
produce a Markdown document that includes:

1. Setup and workholding
2. Operation sequence (face -> rough -> finish -> drill -> chamfer)
3. Tool list (with T# from the tool DB)
4. Feeds and speeds (start values, conservative; cite material from brief)
5. Inspection plan (CMM / calipers / pin gages)
6. Risks (DFM findings + safety factor from FEA)
7. Cosmetic / finish notes

Return only Markdown, no preamble."""


@dataclass
class MfgNotes:
    markdown: str
    generated_by: str = "template"          # "template" | "openai" | ...

    def save(self, path: Path) -> None:
        path.write_text(self.markdown)


def generate_manufacturing_notes(*, brief=None, geometry=None,
                                 reports: list | None = None,
                                 tool_db=None,
                                 llm=None) -> MfgNotes:
    try:
        llm = llm or llm_factory()
        payload = _build_payload(brief, geometry, reports or [], tool_db)
        from ai.base import LLMMessage, LLMRole
        resp = llm.complete([
            LLMMessage(LLMRole.SYSTEM, SYSTEM),
            LLMMessage(LLMRole.USER, payload),
        ], temperature=0.2, max_tokens=2500)
        return MfgNotes(markdown=resp.content, generated_by=llm.name)
    except Exception as e:
        logger.warning(f"[mfg_notes] LLM path failed ({e}); using template.")
        return MfgNotes(markdown=_template_notes(brief, geometry,
                                                reports or [], tool_db),
                        generated_by="template")


def _build_payload(brief, geometry, reports, tool_db) -> str:
    return (
        "DESIGN BRIEF:\n" + json.dumps(brief.to_dict() if brief else {}, indent=2) +
        "\n\nGEOMETRY:\n" + json.dumps(geometry.to_dict() if geometry else {}, indent=2) +
        "\n\nVALIDATION REPORTS:\n" +
        json.dumps([r.to_dict() if hasattr(r, "to_dict") else r for r in reports],
                   indent=2) +
        "\n\nTOOL DB:\n" +
        json.dumps([t.__dict__ for t in (tool_db.tools if tool_db else [])],
                   indent=2) +
        "\n\nNow write the manufacturing notes."
    )


def _stock_from_brief(brief) -> str:
    if not brief or not brief.bbox_mm:
        return ""
    b = brief.bbox_mm
    L = b.get("length", 0); W = b.get("width", 0); T = b.get("thickness",
                                                            b.get("height", 0))
    pad = 3.0
    return f"{L + pad:.1f} x {W + pad:.1f} x {T + pad:.1f} mm"


def _template_notes(brief, geometry, reports, tool_db) -> str:
    tools_md = "\n".join(
        f"- **{t.id}** {t.type} dia {t.diameter_mm}mm "
        f"({t.flutes}F, {t.material}) -- {t.description}"
        for t in (tool_db.tools if tool_db else [])
    ) or "_no tool DB provided_"
    rep_lines = []
    for r in reports:
        d = r.to_dict() if hasattr(r, "to_dict") else r
        rep_lines.append(f"### {d.get('name','?')}: **{d.get('status','?')}**\n"
                         f"```json\n{json.dumps(d, indent=2)}\n```")
    rep_md = "\n\n".join(rep_lines) or "_no reports_"
    stock = _stock_from_brief(brief) if brief else "TBD"
    material = brief.material if brief else "TBD"
    process = brief.process if brief else "cnc_mill"
    sf = (brief.surface_finish_um_ra if brief else None) or "TBD"

    return f"""# Manufacturing Notes -- {brief.name if brief else 'part'}

> Generated by JoyCAD (template fallback). Have a real engineer review.

## 1. Setup and workholding

- Stock: {stock}
- Material: **{material}**
- Process: {process}
- Recommended workholding: vise (soft jaws machined to stock profile)
- Datum: stock bottom face (Z0) and back-left corner (X0Y0)

## 2. Operation sequence

1. **Face** stock to clean top (T1 6mm endmill, 0.5mm depth, 60 percent stepover)
2. **Rough** all pockets with adaptive clearing (T4 10mm, 3mm stepdown)
3. **Finish** walls (T1 6mm, 0.5mm stepdown, full depth)
4. **Drill** all holes (T3 6.6mm drill for M6 clearance)
5. **Chamfer** all hole edges (T2 3mm endmill, 0.5mm chamfer)
6. **Spot** all hole positions before drilling

## 3. Tool list

{tools_md}

## 4. Feeds and speeds (starting points)

| Tool | RPM | Feed (mm/min) | Plunge (mm/min) |
|------|-----|---------------|------------------|
| T1   | 10 000 | 600         | 200              |
| T2   | 12 000 | 300         | 100              |
| T3   |  3 000 | 200         | 80               |
| T4   |  8 000 | 1200        | 400              |

Adjust based on chip color, machine rigidity, and tool life.

## 5. Inspection

- Critical dimensions: per drawing tolerances
- Hole pattern: CMM or pin gage set
- Surface finish: profilometer (Ra {sf} um)
- First-article: full dimensional report

## 6. Validation summary

{rep_md}

## 7. Risks

- Confirm FEA safety factor greater than 1.5 before sign-off.
- Verify no DFM violations remain unaddressed.
- Re-check stock dimensions against `bbox_mm + 3 mm`.
"""
